### PR TITLE
fix: refactor and simplify code, support for registering it as pre

### PR DESCRIPTION
**Pull request by armano2**
see https://github.com/typescript-eslint/typescript-eslint/pull/4128

### CODE REVIEW

**Review by mccleanp — APPROVED** [review]
Many thanks for these changes @armano2. Nice work.

Glad to see the project was useful to someone else.

**Comment by armano2** [comment]
i actually missed README

> This package expects [remark-slug][https://github.com/remarkjs/remark-slug] to be used before it, which is already the case for docusaurus, but may need to be considered if used outside docusaurus.

that's no longer a case, it can be used in `beforeDefaultRemarkPlugins` and its actually better to use it that way as tabs are going to disappear from TOC

**Comment by armano2** [comment]
@mccleanp can you tell me when we can expect release?

**Comment by mccleanp** [comment]
Just published now

**Pull request merged**
